# -*- coding: utf-8 -*-
"""histogram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eh9Uc0GKIee7hz1aATQnS2efE1wXV6t0
"""

import imageio
import numpy as np
import matplotlib.pyplot as plt

# Membaca gambar (ganti 'your_image.jpg' dengan nama gambar Anda)
img = imageio.imread('/content/singkong.jpg')

# Konversi ke grayscale (rata-rata dari nilai RGB)
gray_img = np.mean(img, axis=2).astype(np.uint8)

# Hitung histogram
hist, bins = np.histogram(gray_img.flatten(), bins=256, range=(0, 255))

# Plot histogram
plt.figure(figsize=(10, 6))
plt.bar(bins[:-1], hist, width=1)
plt.xlabel('Intensitas')
plt.ylabel('Jumlah Piksel')
plt.title('Histogram Gambar Grayscale')
plt.show()

# Menampilkan jumlah piksel untuk setiap intensitas
for i, count in enumerate(hist):
    print(f"Intensitas {i}: {count} piksel")

# Mencari intensitas dominan (nilai maksimum dalam histogram)
dominant_intensity = np.argmax(hist)
print(f"Intensitas dominan: {dominant_intensity}")