# -*- coding: utf-8 -*-
"""blue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UauDTIYZNA-3GKAe0nQYktePw4S72c1y
"""

import numpy as np
import imageio
import matplotlib.pyplot as plt

# Membaca gambar
img = imageio.imread('/content/pexels-daniel-dan-7543155-scaled.jpg')

# Fungsi untuk mendapatkan channel warna B (Blue)
def get_blue_channel(image):
    B = image.copy()
    B[:, :, 0] = 0  # Set Red to 0
    B[:, :, 1] = 0  # Set Green to 0
    return B

# Dapatkan channel warna B
blue_channel = get_blue_channel(img)

# Tampilkan channel warna biru
plt.imshow(blue_channel)
plt.title('Blue Channel')
plt.axis('off')
plt.show()