# -*- coding: utf-8 -*-
"""grayscale.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14MHlw0Bm-QTyTOjGnS5IQMaP-xulUTw1
"""

import numpy as np
import imageio
import matplotlib.pyplot as plt

# Membaca gambar
img = imageio.imread('/content/pexels-daniel-dan-7543155-scaled.jpg')

# Fungsi untuk konversi grayscale
def convert_to_grayscale(image):
    # Konversi menggunakan rumus standar grayscale
    grayscale = np.dot(image[..., :3], [0.2989, 0.5870, 0.1140])
    return grayscale.astype(np.uint8)

# Konversi gambar ke grayscale
grayscale_img = convert_to_grayscale(img)

# Tampilkan gambar grayscale
plt.imshow(grayscale_img, cmap='gray')
plt.title('Grayscale Image')
plt.axis('off')
plt.show()