# -*- coding: utf-8 -*-
"""green.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19YGPaTgfFC1-UjcU9gzzXHR_s2yyU4Vd
"""

import numpy as np
import imageio
import matplotlib.pyplot as plt

# Membaca gambar
img = imageio.imread('/content/pexels-daniel-dan-7543155-scaled.jpg')

# Fungsi untuk mendapatkan channel warna G (Green)
def get_green_channel(image):
    G = image.copy()
    G[:, :, 0] = 0  # Set Red to 0
    G[:, :, 2] = 0  # Set Blue to 0
    return G

# Dapatkan channel warna G
green_channel = get_green_channel(img)

# Tampilkan channel warna hijau
plt.imshow(green_channel)
plt.title('Green Channel')
plt.axis('off')
plt.show()